spring.application.name=spring_boot_zero_to_hero
# =========================
# DATABASE CONFIG
# =========================

spring.datasource.url=jdbc:postgresql://localhost:5432/employee
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# auto create/update tables
spring.jpa.hibernate.ddl-auto=update

# show sql in console
spring.jpa.show-sql=true

# pretty formatted sql
spring.jpa.properties.hibernate.format_sql=true

# =========================
# LOGGING
# =========================

logging.level.org.springframework.web=DEBUG
logging.level.com.example=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# =========================
# STATIC FILES
# =========================

# spring.web.resources.static-locations=file:./frontend2/build/

# =========================
# CUSTOM CONFIG PROPERTIES
# =========================

app.features.enable-caching=true
app.features.default-role=ADMIN
app.features.max-login-attempts=10
